In [1]:
import numpy as np

In [3]:
a=np.array([[1,4,5,6,8],[54,8,12,11,35]])

In [10]:
print(a)

[[ 1  4  5  6  8]
 [54  8 12 11 35]]


In [9]:
# Get specific element
a[1,4]

35

In [11]:
#Get element with negetive Index
a[1,-2]

11

In [16]:
# How to get a row 
#how to get a coloum

print(a[1, :])
print(a[: , 2])

[54  8 12 11 35]
[ 5 12]


In [18]:
#Getting little more Fancy
print(a[0,0:5:2])

[1 5 8]


In [21]:
b=np.array([[[1,2],[4,7]],[[4,6],[9,7]]])
print(b)

[[[1 2]
  [4 7]]

 [[4 6]
  [9 7]]]


In [26]:
#Egt a specific element with this type of array(Outside in method)
b[1,0,1]

6