In [1]:
import numpy as np

In [2]:
print("4")

4


In [3]:
my_list=[1,2,3,5,4]
arr=np.array(my_list)

In [4]:
arr

array([1, 2, 3, 5, 4])

In [5]:
my_list1=[1,2,3,5,4]
my_list2=[1,2,3,5,4]
my_list3=[1,2,3,5,4]
arr=np.array([my_list1,my_list2,my_list3])


In [6]:
arr


array([[1, 2, 3, 5, 4],
       [1, 2, 3, 5, 4],
       [1, 2, 3, 5, 4]])

In [7]:
arr.shape


(3, 5)

In [8]:
arr.reshape(5,3)

array([[1, 2, 3],
       [5, 4, 1],
       [2, 3, 5],
       [4, 1, 2],
       [3, 5, 4]])

In [9]:
arr.size

15

In [11]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [12]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[1]

2

In [14]:
arr[:,:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [15]:
arr[0:2,:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [16]:
my_list1=[1,2,3,5,4]
my_list2=[1,2,3,5,4]
my_list3=[1,2,3,5,4]
arr=np.array([my_list1,my_list2,my_list3])

In [17]:
arr


array([[1, 2, 3, 5, 4],
       [1, 2, 3, 5, 4],
       [1, 2, 3, 5, 4]])

In [20]:
arr[0:2,0:2]

array([[1, 2],
       [1, 2]])

In [23]:
arr[1:3,2:4]

array([[3, 5],
       [3, 5]])