In [ ]:
#Different Types of Arrays

In [1]:

import numpy as np;

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros((7,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((2,3),98)

array([[98, 98, 98],
       [98, 98, 98]])

In [8]:
np.random.rand(2,3)

array([[0.48574613, 0.26352046, 0.04881528],
       [0.05832276, 0.73982391, 0.92681341]])

In [9]:
np.random.rand(2,3,6)

array([[[0.51229163, 0.28842123, 0.07050601, 0.95572372, 0.49506769,
         0.14743784],
        [0.62335324, 0.37021589, 0.80218021, 0.49242577, 0.82092926,
         0.35948938],
        [0.37251576, 0.06669996, 0.1521567 , 0.87161795, 0.95617653,
         0.7399144 ]],

       [[0.71227775, 0.51201504, 0.51100136, 0.00202374, 0.29978741,
         0.46583704],
        [0.58982955, 0.19136594, 0.35735003, 0.78706984, 0.15934836,
         0.82114527],
        [0.86685247, 0.71173842, 0.59682966, 0.69876933, 0.48618406,
         0.40400766]]])

In [13]:
np.random.random_sample(5)

array([0.94104967, 0.54280477, 0.80123183, 0.23976605, 0.92339655])

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])